version: '3.3'
networks:
  default:
    external:
      name: external-nextjs
services:
  postgresql:
    restart: always
    image: postgres:12.9
    ports:
      - '15432:5432'
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=countrydb
      - PG_TRUST_LOCALNET=true
      - PG_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
