version: '3.3'
services:
  postgresql:
    restart: always
    image: postgres:12.9
    ports:
      - '5432:5432'
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=countrydb
      - PGUSER=postgres
      - PG_TRUST_LOCALNET=true
    volumes:
      - /var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
